Repository brain-tec/product-attribute, pull requests merged in 2022-09, with the labels that each got.

#644 Syncing from upstream OCA/product-attribute (14.0)
  product_attribute_value_menu/i18n/it.po
Labels: 14.0

#645 [MIG] product custom info
  product_custom_info/README.rst
  product_custom_info/__init__.py
  product_custom_info/__manifest__.py
  product_custom_info/i18n/ca.po
  product_custom_info/i18n/es.po
  product_custom_info/i18n/it.po
  product_custom_info/i18n/product_custom_info.pot
  product_custom_info/i18n/pt.po
  product_custom_info/models/__init__.py
  product_custom_info/models/product_product.py
  product_custom_info/models/product_template.py
  product_custom_info/readme/CONFIGURE.rst
  product_custom_info/readme/CONTRIBUTORS.rst
  product_custom_info/readme/DESCRIPTION.rst
  product_custom_info/readme/INSTALL.rst
  product_custom_info/readme/USAGE.rst
  product_custom_info/static/description/icon.png
  product_custom_info/static/description/index.html
  product_custom_info/tests/__init__.py
  product_custom_info/tests/test_product_custom_info.py
  product_custom_info/views/product_product_view.xml
  product_custom_info/views/product_template_view.xml
  setup/product_custom_info/odoo/addons/product_custom_info
  setup/product_custom_info/setup.py
Labels: 15.0.project_sa_650

#646 Syncing from upstream OCA/product-attribute (14.0)
  README.md
  product_supplierinfo_for_customer/README.rst
  product_supplierinfo_for_customer/__manifest__.py
  product_supplierinfo_for_customer/readme/DESCRIPTION.rst
  product_supplierinfo_for_customer/static/description/index.html
  product_supplierinfo_for_customer/views/product_view.xml
Labels: 14.0

#647 Syncing from upstream OCA/product-attribute (15.0)
  README.md
  product_attribute_value_menu/README.rst
  product_attribute_value_menu/__init__.py
  product_attribute_value_menu/__manifest__.py
  product_attribute_value_menu/i18n/it.po
  product_attribute_value_menu/i18n/product_attribute_value_menu.pot
  product_attribute_value_menu/models/__init__.py
  product_attribute_value_menu/models/product_attribute_value.py
  product_attribute_value_menu/readme/CONFIGURE.rst
  product_attribute_value_menu/readme/CONTRIBUTORS.rst
  product_attribute_value_menu/readme/DESCRIPTION.rst
  product_attribute_value_menu/readme/USAGE.rst
  product_attribute_value_menu/static/description/icon.png
  product_attribute_value_menu/static/description/index.html
  product_attribute_value_menu/views/product_attribute_value_views.xml
  product_attribute_value_menu/views/product_template_attribute_value_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/product_attribute_value_menu/odoo/addons/product_attribute_value_menu
  setup/product_attribute_value_menu/setup.py
Labels: 15.0

#649 Syncing from upstream OCA/product-attribute (14.0)
  README.md
  product_supplierinfo_stock_picking_type/README.rst
  product_supplierinfo_stock_picking_type/__init__.py
  product_supplierinfo_stock_picking_type/__manifest__.py
  product_supplierinfo_stock_picking_type/i18n/es.po
  product_supplierinfo_stock_picking_type/i18n/product_supplierinfo_stock_picking_type.pot
  product_supplierinfo_stock_picking_type/models/__init__.py
  product_supplierinfo_stock_picking_type/models/product_product.py
  product_supplierinfo_stock_picking_type/models/product_supplierinfo.py
  product_supplierinfo_stock_picking_type/models/purchase_order.py
  product_supplierinfo_stock_picking_type/readme/CONFIGURE.rst
  product_supplierinfo_stock_picking_type/readme/CONTRIBUTORS.rst
  product_supplierinfo_stock_picking_type/readme/DESCRIPTION.rst
  product_supplierinfo_stock_picking_type/readme/USAGE.rst
  product_supplierinfo_stock_picking_type/static/description/icon.png
  product_supplierinfo_stock_picking_type/static/description/index.html
  product_supplierinfo_stock_picking_type/tests/__init__.py
  product_supplierinfo_stock_picking_type/tests/test_product_supplierinfo_stock_picking_type.py
  product_supplierinfo_stock_picking_type/views/product_supplierinfo_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/product_supplierinfo_stock_picking_type/odoo/addons/product_supplierinfo_stock_picking_type
  setup/product_supplierinfo_stock_picking_type/setup.py
Labels: 14.0

#650 Syncing from upstream OCA/product-attribute (14.0)
  README.md
  product_pricelist_direct_print_company_group/README.rst
  product_pricelist_direct_print_company_group/__init__.py
  product_pricelist_direct_print_company_group/__manifest__.py
  product_pricelist_direct_print_company_group/i18n/product_pricelist_direct_print_company_group.pot
  product_pricelist_direct_print_company_group/readme/CONTRIBUTORS.rst
  product_pricelist_direct_print_company_group/readme/DESCRIPTION.rst
  product_pricelist_direct_print_company_group/readme/USAGE.rst
  product_pricelist_direct_print_company_group/static/description/icon.png
  product_pricelist_direct_print_company_group/static/description/index.html
  product_pricelist_direct_print_company_group/wizards/__init__.py
  product_pricelist_direct_print_company_group/wizards/product_pricelist_print.py
  product_secondary_unit/i18n/es_AR.po
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/product_pricelist_direct_print_company_group/odoo/addons/product_pricelist_direct_print_company_group
  setup/product_pricelist_direct_print_company_group/setup.py
Labels: 14.0

#651 Syncing from upstream OCA/product-attribute (15.0)
  README.md
  product_attribute_value_menu/__manifest__.py
  product_attribute_value_menu/views/product_attribute_value_views.xml
Labels: 15.0

#652 Syncing from upstream OCA/product-attribute (14.0)
  product_manufacturer/i18n/es_AR.po
  product_sequence/i18n/es_AR.po
Labels: 14.0

#653 Syncing from upstream OCA/product-attribute (15.0)
  product_manufacturer/i18n/es_AR.po
  product_sequence/i18n/es_AR.po
Labels: 15.0

#654 Syncing from upstream OCA/product-attribute (14.0)
  product_weight/i18n/es_AR.po
Labels: 14.0

#655 Syncing from upstream OCA/product-attribute (15.0)
  README.md
  product_restricted_type/README.rst
  product_restricted_type/__init__.py
  product_restricted_type/__manifest__.py
  product_restricted_type/i18n/ca.po
  product_restricted_type/i18n/es.po
  product_restricted_type/i18n/product_restricted_type.pot
  product_restricted_type/models/__init__.py
  product_restricted_type/models/product.py
  product_restricted_type/models/product_template.py
  product_restricted_type/readme/CONTRIBUTORS.rst
  product_restricted_type/readme/DESCRIPTION.rst
  product_restricted_type/readme/USAGE.rst
  product_restricted_type/static/description/icon.png
  product_restricted_type/static/description/index.html
  product_restricted_type/tests/__init__.py
  product_restricted_type/tests/test_product_restricted_type.py
  product_restricted_type/views/product_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/product_restricted_type/odoo/addons/product_restricted_type
  setup/product_restricted_type/setup.py
Labels: 15.0

#656 Syncing from upstream OCA/product-attribute (13.0)
  README.md
  product_template_tags/README.rst
  product_template_tags/__manifest__.py
  product_template_tags/readme/USAGE.rst
  product_template_tags/static/description/index.html
  product_template_tags/views/product_product.xml
  product_template_tags/views/product_template.xml
Labels: 13.0

#657 Syncing from upstream OCA/product-attribute (14.0)
  product_pricelist_revision/i18n/it.po
Labels: 14.0
