Repository brain-tec/product-attribute, pull requests merged in 2023-12, with the labels that each got.

#980 Syncing from upstream OCA/product-attribute (14.0)
  README.md
  product_lot_sequence/README.rst
  product_lot_sequence/__manifest__.py
  product_lot_sequence/i18n/ca.po
  product_lot_sequence/i18n/es.po
  product_lot_sequence/i18n/fr.po
  product_lot_sequence/i18n/it.po
  product_lot_sequence/i18n/product_lot_sequence.pot
  product_lot_sequence/models/__init__.py
  product_lot_sequence/models/product.py
  product_lot_sequence/models/res_company.py
  product_lot_sequence/models/res_config_settings.py
  product_lot_sequence/readme/CONTRIBUTORS.rst
  product_lot_sequence/readme/USAGE.rst
  product_lot_sequence/static/description/index.html
  product_lot_sequence/tests/test_product_lot_sequence.py
  product_lot_sequence/views/res_config_settings.xml
Labels: 14.0

#981 Syncing from upstream OCA/product-attribute (16.0)
  README.md
  product_lot_sequence/README.rst
  product_lot_sequence/__init__.py
  product_lot_sequence/__manifest__.py
  product_lot_sequence/data/ir_config_parameter.xml
  product_lot_sequence/i18n/ca.po
  product_lot_sequence/i18n/es.po
  product_lot_sequence/i18n/fr.po
  product_lot_sequence/i18n/product_lot_sequence.pot
  product_lot_sequence/models/__init__.py
  product_lot_sequence/models/product.py
  product_lot_sequence/models/res_company.py
  product_lot_sequence/models/res_config_settings.py
  product_lot_sequence/models/stock_lot.py
  product_lot_sequence/readme/CONFIGURE.rst
  product_lot_sequence/readme/CONTRIBUTORS.rst
  product_lot_sequence/readme/DESCRIPTION.rst
  product_lot_sequence/readme/USAGE.rst
  product_lot_sequence/static/description/icon.png
  product_lot_sequence/static/description/index.html
  product_lot_sequence/tests/__init__.py
  product_lot_sequence/tests/test_product_lot_sequence.py
  product_lot_sequence/views/product_views.xml
  product_lot_sequence/views/res_config_settings_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/product_lot_sequence/odoo/addons/product_lot_sequence
  setup/product_lot_sequence/setup.py
Labels: 16.0

#982 Syncing from upstream OCA/product-attribute (13.0)
  product_exception/i18n/it.po
Labels: 13.0

#983 Syncing from upstream OCA/product-attribute (14.0)
  README.md
  product_internal_reference_generator/README.rst
  product_internal_reference_generator/__manifest__.py
  product_internal_reference_generator/security/ir.model.access.csv
  product_internal_reference_generator/static/description/index.html
  product_internal_reference_generator/views/product.xml
  product_lot_sequence/i18n/it.po
  product_tier_validation/i18n/it.po
Labels: 14.0

#984 Syncing from upstream OCA/product-attribute (15.0)
  product_lot_sequence/i18n/it.po
Labels: 15.0

#985 Syncing from upstream OCA/product-attribute (16.0)
  product_country_restriction/i18n/it.po
  product_lot_sequence/i18n/it.po
Labels: 16.0

#986 Syncing from upstream OCA/product-attribute (16.0)
  product_country_restriction/i18n/es.po
  product_lot_sequence/i18n/es.po
Labels: 16.0

#987 Syncing from upstream OCA/product-attribute (17.0)
  README.md
  product_dimension/README.rst
  product_dimension/__init__.py
  product_dimension/__manifest__.py
  product_dimension/i18n/ca.po
  product_dimension/i18n/de.po
  product_dimension/i18n/es.po
  product_dimension/i18n/fr.po
  product_dimension/i18n/fr_FR.po
  product_dimension/i18n/it.po
  product_dimension/i18n/product_dimension.pot
  product_dimension/i18n/pt.po
  product_dimension/models/__init__.py
  product_dimension/models/product_product.py
  product_dimension/models/product_template.py
  product_dimension/pyproject.toml
  product_dimension/readme/CONTRIBUTORS.md
  product_dimension/readme/CREDITS.md
  product_dimension/readme/DESCRIPTION.md
  product_dimension/readme/HISTORY.md
  product_dimension/readme/USAGE.md
  product_dimension/static/description/icon.png
  product_dimension/static/description/index.html
  product_dimension/tests/__init__.py
  product_dimension/tests/test_compute_volume.py
  product_dimension/tests/test_template.py
  product_dimension/views/product_view.xml
  setup/_metapackage/pyproject.toml
Labels: 17.0

#988 Syncing from upstream OCA/product-attribute (16.0)
  product_pricelist_item_list_view/i18n/fr.po
Labels: 16.0

#989 Syncing from upstream OCA/product-attribute (16.0)
  README.md
  product_print_category/README.rst
  product_print_category/__manifest__.py
  product_print_category/models/product_print_category_mixin.py
  product_print_category/static/description/index.html
Labels: 16.0

#990 Syncing from upstream OCA/product-attribute (13.0)
  product_attribute_value_menu/i18n/it.po
Labels: 13.0

#991 Syncing from upstream OCA/product-attribute (14.0)
  product_attribute_value_menu/i18n/it.po
  product_tier_validation/i18n/it.po
Labels: 14.0

#992 Syncing from upstream OCA/product-attribute (15.0)
  product_attribute_value_menu/i18n/it.po
Labels: 15.0

#994 [t140653] MIG V16 | prepare OCA fork to migrate field names
  product_dimension/migrations/16.0.1.1.0/pre-migration.py
Labels: 16.0.project_xp_228

#995 Syncing from upstream OCA/product-attribute (8.0)
  product_price_history/i18n/it.po
Labels: 8.0

#996 Syncing from upstream OCA/product-attribute (12.0)
  product_price_history/i18n/it.po
Labels: 12.0

#997 Syncing from upstream OCA/product-attribute (14.0)
  README.md
  product_internal_reference_generator/README.rst
  product_internal_reference_generator/__manifest__.py
  product_internal_reference_generator/i18n/it.po
  product_internal_reference_generator/i18n/product_internal_reference_generator.pot
  product_internal_reference_generator/models/__init__.py
  product_internal_reference_generator/models/product_code_sequence.py
  product_internal_reference_generator/models/product_template.py
  product_internal_reference_generator/models/res_company.py
  product_internal_reference_generator/models/res_config_settings.py
  product_internal_reference_generator/readme/DESCRIPTION.rst
  product_internal_reference_generator/readme/USAGE.rst
  product_internal_reference_generator/security/groups.xml
  product_internal_reference_generator/security/ir.model.access.csv
  product_internal_reference_generator/static/description/index.html
  product_internal_reference_generator/tests/test_product_internal_reference_generator.py
  product_internal_reference_generator/views/product.xml
  product_internal_reference_generator/views/res_config_settings.xml
Labels: 14.0

#998 Syncing from upstream OCA/product-attribute (16.0)
  product_set/i18n/es.po
Labels: 16.0

#999 Syncing from upstream OCA/product-attribute (12.0)
  product_category_type/i18n/it.po
Labels: 12.0

#1001 Syncing from upstream OCA/product-attribute (16.0)
  product_category_type/i18n/it.po
  product_packaging_container_deposit/i18n/it.po
  product_set/i18n/it.po
Labels: 16.0

#1002 Syncing from upstream OCA/product-attribute (14.0)
  README.md
  product_category_description/README.rst
  product_category_description/__init__.py
  product_category_description/__manifest__.py
  product_category_description/i18n/product_category_description.pot
  product_category_description/models/__init__.py
  product_category_description/models/product_category.py
  product_category_description/readme/CONTRIBUTORS.rst
  product_category_description/readme/DESCRIPTION.rst
  product_category_description/static/description/icon.png
  product_category_description/static/description/index.html
  product_category_description/views/product_category.xml
  product_search_by_display_name/README.rst
  product_search_by_display_name/__init__.py
  product_search_by_display_name/__manifest__.py
  product_search_by_display_name/i18n/product_search_by_display_name.pot
  product_search_by_display_name/models/__init__.py
  product_search_by_display_name/models/product_product.py
  product_search_by_display_name/models/product_template.py
  product_search_by_display_name/readme/CONTRIBUTORS.rst
  product_search_by_display_name/readme/CREDITS.rst
  product_search_by_display_name/readme/DESCRIPTION.rst
  product_search_by_display_name/static/description/icon.png
  product_search_by_display_name/static/description/index.html
  product_search_by_display_name/tests/__init__.py
  product_search_by_display_name/tests/test_product_search_by_display_name.py
  product_search_by_display_name/views/product_template.xml
  product_tier_validation/i18n/it.po
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/product_category_description/odoo/addons/product_category_description
  setup/product_category_description/setup.py
  setup/product_search_by_display_name/odoo/addons/product_search_by_display_name
  setup/product_search_by_display_name/setup.py
Labels: 14.0

#1004 Syncing from upstream OCA/product-attribute (14.0)
  product_tier_validation/i18n/it.po
Labels: 14.0

#1005 Syncing from upstream OCA/product-attribute (16.0)
  product_product_template_link/i18n/it.po
  product_profile/i18n/it.po
Labels: 16.0

#1006 Syncing from upstream OCA/product-attribute (14.0)
  product_category_description/i18n/it.po
  product_search_by_display_name/i18n/it.po
Labels: 14.0

#1007 Syncing from upstream OCA/product-attribute (16.0)
  product_packaging_dimension/i18n/it.po
  product_profile/i18n/it.po
Labels: 16.0

#1008 Syncing from upstream OCA/product-attribute (14.0)
  base_product_mass_addition/i18n/de.po
  product_dimension/i18n/de.po
  product_manufacturer/i18n/de.po
  product_medical/i18n/de.po
  product_profile/i18n/de.po
  product_restricted_type/i18n/de.po
  product_secondary_unit/i18n/de.po
  product_sequence/i18n/de.po
  product_state/i18n/de.po
  product_supplierinfo_for_customer/i18n/de.po
  product_template_tags/i18n/de.po
  uom_extra_data/i18n/de.po
Labels: 14.0

#1009 Syncing from upstream OCA/product-attribute (16.0)
  product_attribute_archive/i18n/es.po
  product_attribute_value_menu/i18n/es.po
  product_code_unique/i18n/es.po
  product_packaging_container_deposit/i18n/es.po
  product_packaging_level_purchasable/i18n/es.po
  product_packaging_level_salable/i18n/es.po
  product_product_template_link/i18n/es.po
  product_route_mto/i18n/es.po
  product_sale_description/i18n/es.po
  product_uom_po_domain/i18n/es.po
  product_variant_attribute_name_manager/i18n/es.po
  stock_production_lot_expired_date/i18n/es.po
Labels: 16.0

#1010 Syncing from upstream OCA/product-attribute (16.0)
  product_profile/i18n/nl_NL.po
Labels: 16.0
