Repository brain-tec/product-attribute, pull requests merged in 2023-04, with the labels that each got.

#755 Syncing from upstream OCA/product-attribute (12.0)
  product_secondary_unit/i18n/sl.po
Labels: 12.0

#756 Syncing from upstream OCA/product-attribute (14.0)
  product_profile/i18n/sl.po
  product_template_tags/i18n/sl.po
  product_weight/i18n/sl.po
Labels: 14.0

#757 Syncing from upstream OCA/product-attribute (15.0)
  README.md
  product_sticker/__manifest__.py
  product_sticker/i18n/product_sticker.pot
  product_sticker/models/product_sticker.py
Labels: 15.0

#758 Syncing from upstream OCA/product-attribute (16.0)
  README.md
  product_supplierinfo_for_customer/README.rst
  product_supplierinfo_for_customer/__init__.py
  product_supplierinfo_for_customer/__manifest__.py
  product_supplierinfo_for_customer/demo/product_demo.xml
  product_supplierinfo_for_customer/i18n/ca.po
  product_supplierinfo_for_customer/i18n/de.po
  product_supplierinfo_for_customer/i18n/es.po
  product_supplierinfo_for_customer/i18n/fr.po
  product_supplierinfo_for_customer/i18n/product_supplierinfo_for_customer.pot
  product_supplierinfo_for_customer/i18n/sl.po
  product_supplierinfo_for_customer/migrations/16.0.1.0.0/pre-migration.py
  product_supplierinfo_for_customer/models/__init__.py
  product_supplierinfo_for_customer/models/product_customerinfo.py
  product_supplierinfo_for_customer/models/product_pricelist.py
  product_supplierinfo_for_customer/models/product_product.py
  product_supplierinfo_for_customer/models/product_supplierinfo.py
  product_supplierinfo_for_customer/models/product_template.py
  product_supplierinfo_for_customer/models/res_partner.py
  product_supplierinfo_for_customer/readme/CONFIGURE.rst
  product_supplierinfo_for_customer/readme/CONTRIBUTORS.rst
  product_supplierinfo_for_customer/readme/DESCRIPTION.rst
  product_supplierinfo_for_customer/readme/ROADMAP.rst
  product_supplierinfo_for_customer/readme/USAGE.rst
  product_supplierinfo_for_customer/security/ir.model.access.csv
  product_supplierinfo_for_customer/static/description/icon.png
  product_supplierinfo_for_customer/static/description/index.html
  product_supplierinfo_for_customer/static/xls/product_customerinfo.xls
  product_supplierinfo_for_customer/tests/__init__.py
  product_supplierinfo_for_customer/tests/test_product_supplierinfo_for_customer.py
  product_supplierinfo_for_customer/views/product_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/product_supplierinfo_for_customer/odoo/addons/product_supplierinfo_for_customer
  setup/product_supplierinfo_for_customer/setup.py
Labels: 16.0

#759 Syncing from upstream OCA/product-attribute (13.0)
  README.md
  product_pricelist_direct_print/__manifest__.py
  product_pricelist_direct_print/wizards/product_pricelist_print_view.xml
Labels: 13.0

#760 Syncing from upstream OCA/product-attribute (14.0)
  product_assortment_description/i18n/it.po
Labels: 14.0

#761 Syncing from upstream OCA/product-attribute (15.0)
  README.md
  base_product_mass_addition/README.rst
  base_product_mass_addition/__init__.py
  base_product_mass_addition/__manifest__.py
  base_product_mass_addition/i18n/base_product_mass_addition.pot
  base_product_mass_addition/i18n/fr.po
  base_product_mass_addition/models/__init__.py
  base_product_mass_addition/models/product_mass_addition.py
  base_product_mass_addition/models/product_product.py
  base_product_mass_addition/readme/CONTRIBUTORS.rst
  base_product_mass_addition/readme/DESCRIPTION.rst
  base_product_mass_addition/readme/ROADMAP.rst
  base_product_mass_addition/static/description/filter.png
  base_product_mass_addition/static/description/icon.png
  base_product_mass_addition/static/description/index.html
  base_product_mass_addition/static/description/po-product.png
  base_product_mass_addition/static/description/po.png
  base_product_mass_addition/tests/__init__.py
  base_product_mass_addition/tests/models/order.py
  base_product_mass_addition/tests/test_product_mass_addition.py
  base_product_mass_addition/views/product_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/base_product_mass_addition/odoo/addons/base_product_mass_addition
  setup/base_product_mass_addition/setup.py
Labels: 15.0

#762 Syncing from upstream OCA/product-attribute (8.0)
  product_price_history/i18n/it.po
Labels: 8.0

#763 Syncing from upstream OCA/product-attribute (12.0)
  product_price_history/i18n/it.po
  product_pricelist_revision/i18n/it.po
Labels: 12.0

#764 Syncing from upstream OCA/product-attribute (14.0)
  product_assortment_description/i18n/it.po
Labels: 14.0

#765 Syncing from upstream OCA/product-attribute (15.0)
  base_product_mass_addition/i18n/fr.po
Labels: 15.0

#766 Syncing from upstream OCA/product-attribute (12.0)
  product_pricelist_direct_print/i18n/it.po
Labels: 12.0

#767 Syncing from upstream OCA/product-attribute (14.0)
  product_assortment_description/i18n/it.po
Labels: 14.0

#768 Syncing from upstream OCA/product-attribute (12.0)
  product_pricelist_direct_print/i18n/it.po
Labels: 12.0

#769 Syncing from upstream OCA/product-attribute (15.0)
  README.md
  product_multi_price/README.rst
  product_multi_price/__init__.py
  product_multi_price/__manifest__.py
  product_multi_price/demo/multi_price_demo_data.xml
  product_multi_price/hooks.py
  product_multi_price/i18n/ca.po
  product_multi_price/i18n/es.po
  product_multi_price/i18n/it.po
  product_multi_price/i18n/product_multi_price.pot
  product_multi_price/models/__init__.py
  product_multi_price/models/product_multi_price.py
  product_multi_price/models/product_pricelist.py
  product_multi_price/models/product_product.py
  product_multi_price/models/product_template.py
  product_multi_price/readme/CONFIGURE.rst
  product_multi_price/readme/CONTRIBUTORS.rst
  product_multi_price/readme/DESCRIPTION.rst
  product_multi_price/readme/ROADMAP.rst
  product_multi_price/readme/USAGE.rst
  product_multi_price/security/ir.model.access.csv
  product_multi_price/security/multi_price_security.xml
  product_multi_price/static/description/icon.png
  product_multi_price/static/description/index.html
  product_multi_price/tests/__init__.py
  product_multi_price/tests/test_product_multi_price.py
  product_multi_price/views/multi_price_views.xml
  product_multi_price/views/product_pricelist_views.xml
  product_multi_price/views/product_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/product_multi_price/odoo/addons/product_multi_price
  setup/product_multi_price/setup.py
Labels: 15.0

#770 Syncing from upstream OCA/product-attribute (14.0)
  product_assortment_description/i18n/it.po
Labels: 14.0

#771 Syncing from upstream OCA/product-attribute (15.0)
  base_product_mass_addition/i18n/es.po
Labels: 15.0

#772 Syncing from upstream OCA/product-attribute (12.0)
  product_brand/i18n/it.po
  product_profile/i18n/it.po
  product_template_tags/i18n/it.po
  product_weight/i18n/it.po
Labels: 12.0

#773 Syncing from upstream OCA/product-attribute (13.0)
  product_template_tags/i18n/it.po
  product_weight/i18n/it.po
Labels: 13.0

#774 Syncing from upstream OCA/product-attribute (14.0)
  product_profile/i18n/it.po
Labels: 14.0

#775 Syncing from upstream OCA/product-attribute (15.0)
  product_template_tags/i18n/it.po
Labels: 15.0

#776 Syncing from upstream OCA/product-attribute (12.0)
  product_pricelist_supplierinfo/i18n/it.po
  product_standard_price_tax_included/__manifest__.py
  product_standard_price_tax_included/i18n/ca.po
  product_standard_price_tax_included/i18n/de.po
  product_standard_price_tax_included/i18n/es.po
  product_standard_price_tax_included/i18n/fr.po
  product_standard_price_tax_included/i18n/product_standard_price_tax_included.pot
  product_standard_price_tax_included/i18n/sl.po
  product_standard_price_tax_included/models/__init__.py
  product_standard_price_tax_included/models/product_template.py
  product_standard_price_tax_included/tests/test_module.py
Labels: 12.0

#777 Syncing from upstream OCA/product-attribute (13.0)
  product_pricelist_supplierinfo/i18n/it.po
Labels: 13.0

#778 Syncing from upstream OCA/product-attribute (14.0)
  product_pricelist_supplierinfo/i18n/it.po
Labels: 14.0

#779 Syncing from upstream OCA/product-attribute (15.0)
  product_pricelist_supplierinfo/i18n/it.po
Labels: 15.0

#780 [16.0][MIG] product_secondary_unit
  product_secondary_unit/README.rst
  product_secondary_unit/__init__.py
  product_secondary_unit/__manifest__.py
  product_secondary_unit/i18n/es.po
  product_secondary_unit/i18n/es_MX.po
  product_secondary_unit/i18n/fr.po
  product_secondary_unit/i18n/product_secondary_unit.pot
  product_secondary_unit/i18n/zh_CN.po
  product_secondary_unit/models/__init__.py
  product_secondary_unit/models/product_product.py
  product_secondary_unit/models/product_second_unit.py
  product_secondary_unit/models/product_secondary_unit_mixin.py
  product_secondary_unit/models/product_template.py
  product_secondary_unit/readme/CONTRIBUTORS.rst
  product_secondary_unit/readme/DESCRIPTION.rst
  product_secondary_unit/readme/USAGE.rst
  product_secondary_unit/security/ir.model.access.csv
  product_secondary_unit/static/description/icon.png
  product_secondary_unit/static/description/index.html
  product_secondary_unit/tests/__init__.py
  product_secondary_unit/tests/models.py
  product_secondary_unit/tests/test_product_second_unit.py
  product_secondary_unit/tests/test_secondary_unit_mixin.py
  product_secondary_unit/views/product_views.xml
  requirements.txt
  setup/product_secondary_unit/odoo/addons/product_secondary_unit
  setup/product_secondary_unit/setup.py
Labels: 16.0.project_ba_688

#781 [t136753][FIX] form view in product template
  product_secondary_unit/views/product_views.xml
Labels: 16.0.project_ba_688

#783 Syncing from upstream OCA/product-attribute (14.0)
  product_template_tags/i18n/it.po
  purchase_product_template_tags/i18n/it.po
  sale_product_template_tags/i18n/it.po
  stock_product_template_tags/i18n/it.po
Labels: 14.0

#784 Syncing from upstream OCA/product-attribute (15.0)
  product_template_tags/i18n/it.po
  purchase_product_template_tags/i18n/it.po
  sale_product_template_tags/i18n/it.po
  stock_product_template_tags/i18n/it.po
Labels: 15.0

#785 Syncing from upstream OCA/product-attribute (16.0)
  sale_product_template_tags/i18n/it.po
Labels: 16.0

#786 Syncing from upstream OCA/product-attribute (16.0)
  README.md
  product_attribute_archive/README.rst
  product_attribute_archive/__init__.py
  product_attribute_archive/__manifest__.py
  product_attribute_archive/i18n/product_attribute_archive.pot
  product_attribute_archive/models/__init__.py
  product_attribute_archive/models/product_attribute.py
  product_attribute_archive/models/product_attribute_value.py
  product_attribute_archive/readme/CONTRIBUTORS.rst
  product_attribute_archive/readme/DESCRIPTION.rst
  product_attribute_archive/readme/USAGE.rst
  product_attribute_archive/static/description/icon.png
  product_attribute_archive/static/description/index.html
  product_attribute_archive/views/product_attribute.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/product_attribute_archive/odoo/addons/product_attribute_archive
  setup/product_attribute_archive/setup.py
Labels: 16.0

#787 Syncing from upstream OCA/product-attribute (14.0)
  product_assortment_description/i18n/it.po
Labels: 14.0

#788 Syncing from upstream OCA/product-attribute (16.0)
  README.md
  product_assortment/i18n/it.po
  product_attribute_archive/i18n/it.po
  product_category_active/i18n/it.po
  product_category_code/i18n/it.po
  product_code_unique/i18n/it.po
  product_cost_security/README.rst
  product_cost_security/__init__.py
  product_cost_security/__manifest__.py
  product_cost_security/i18n/ar.po
  product_cost_security/i18n/ca.po
  product_cost_security/i18n/es.po
  product_cost_security/i18n/it.po
  product_cost_security/i18n/product_cost_security.pot
  product_cost_security/models/__init__.py
  product_cost_security/models/product_product.py
  product_cost_security/models/product_template.py
  product_cost_security/readme/CONFIGURE.rst
  product_cost_security/readme/CONTRIBUTORS.rst
  product_cost_security/readme/DESCRIPTION.rst
  product_cost_security/readme/USAGE.rst
  product_cost_security/security/product_cost_security.xml
  product_cost_security/static/description/icon.png
  product_cost_security/static/description/index.html
  product_cost_security/tests/__init__.py
  product_cost_security/tests/test_product_cost_security.py
  product_cost_security/views/product_views.xml
  product_dimension/i18n/it.po
  product_expiry_configurable/i18n/it.po
  product_logistics_uom/i18n/it.po
  product_manufacturer/i18n/it.po
  product_packaging_dimension/i18n/it.po
  product_route_mto/i18n/it.po
  product_sequence/i18n/it.po
  product_state/i18n/it.po
  product_supplierinfo_for_customer/i18n/it.po
  product_template_has_one_variant/i18n/it.po
  product_uom_measure_type/i18n/it.po
  product_uom_updatable/i18n/it.po
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/product_cost_security/odoo/addons/product_cost_security
  setup/product_cost_security/setup.py
  stock_production_lot_expired_date/i18n/it.po
Labels: 16.0

#789 Syncing from upstream OCA/product-attribute (14.0)
  product_secondary_unit/i18n/fr.po
Labels: 14.0
