Repository brain-tec/product-attribute, pull requests merged in 2024-10, with the labels that each got.

#1160 Syncing from upstream OCA/product-attribute (16.0)
  README.md
  product_pricelist_simulation/README.rst
  product_pricelist_simulation/__manifest__.py
  product_pricelist_simulation/security/ir.model.access.csv
  product_pricelist_simulation/static/description/index.html
Labels: 16.0

#1161 Syncing from upstream OCA/product-attribute (17.0)
  README.md
  product_print_category/README.rst
  product_print_category/__manifest__.py
  product_print_category/security/ir.model.access.csv
  product_print_category/static/description/index.html
Labels: 17.0

#1162 Syncing from upstream OCA/product-attribute (16.0)
  product_optional_product_quantity/i18n/it.po
Labels: 16.0

#1163 Syncing from upstream OCA/product-attribute (16.0)
  README.md
  product_cost_security/README.rst
  product_cost_security/__manifest__.py
  product_cost_security/static/description/index.html
  product_cost_security/views/product_views.xml
Labels: 16.0

#1164 Syncing from upstream OCA/product-attribute (15.0)
  README.md
  product_assortment/README.rst
  product_assortment/__manifest__.py
  product_assortment/i18n/ca.po
  product_assortment/i18n/es.po
  product_assortment/i18n/it.po
  product_assortment/i18n/product_assortment.pot
  product_assortment/models/__init__.py
  product_assortment/models/ir_rule.py
  product_assortment/security/product_assortment_security.xml
  product_assortment/static/description/index.html
  product_assortment/views/product_assortment.xml
  product_assortment/views/res_partner_view.xml
Labels: 15.0

#1165 Syncing from upstream OCA/product-attribute (17.0)
  README.md
  product_logistics_uom/i18n/de.po
  product_logistics_uom/i18n/es.po
  product_logistics_uom/i18n/it.po
  product_logistics_uom/i18n/product_logistics_uom.pot
  product_logistics_uom/i18n/pt_BR.po
  product_net_weight/README.rst
  product_net_weight/__init__.py
  product_net_weight/__manifest__.py
  product_net_weight/demo/product_product.xml
  product_net_weight/i18n/es.po
  product_net_weight/i18n/fr.po
  product_net_weight/i18n/it.po
  product_net_weight/i18n/product_net_weight.pot
  product_net_weight/models/__init__.py
  product_net_weight/models/product_product.py
  product_net_weight/models/product_template.py
  product_net_weight/pyproject.toml
  product_net_weight/readme/CONTRIBUTORS.md
  product_net_weight/readme/DESCRIPTION.md
  product_net_weight/readme/ROADMAP.md
  product_net_weight/readme/USAGE.md
  product_net_weight/static/description/icon.png
  product_net_weight/static/description/index.html
  product_net_weight/static/description/product_form.png
  product_net_weight/tests/__init__.py
  product_net_weight/tests/test_product_net_weight.py
  product_net_weight/views/view_product_product.xml
  product_net_weight/views/view_product_template.xml
  setup/_metapackage/pyproject.toml
Labels: 17.0

#1166 Syncing from upstream OCA/product-attribute (16.0)
  README.md
  product_pricelist_alternative/README.rst
  product_pricelist_alternative/__manifest__.py
  product_pricelist_alternative/i18n/fr.po
  product_pricelist_alternative/i18n/it.po
  product_pricelist_alternative/i18n/product_pricelist_alternative.pot
  product_pricelist_alternative/models/product_pricelist.py
  product_pricelist_alternative/models/product_pricelist_item.py
  product_pricelist_alternative/static/description/index.html
  product_pricelist_alternative/tests/test_pricelist_alternative.py
Labels: 16.0

#1167 Syncing from upstream OCA/product-attribute (16.0)
  README.md
  product_packaging_container_deposit/README.rst
  product_packaging_container_deposit/__manifest__.py
  product_packaging_container_deposit/models/container_deposit_order_mixin.py
  product_packaging_container_deposit/static/description/index.html
Labels: 16.0

#1168 Syncing from upstream OCA/product-attribute (16.0)
  product_pricelist_alternative/i18n/it.po
Labels: 16.0

#1169 Syncing from upstream OCA/product-attribute (16.0)
  README.md
  product_english_name/README.rst
  product_english_name/__init__.py
  product_english_name/__manifest__.py
  product_english_name/i18n/product_english_name.pot
  product_english_name/models/__init__.py
  product_english_name/models/product_template.py
  product_english_name/readme/CONFIGURE.rst
  product_english_name/readme/CONTRIBUTORS.rst
  product_english_name/readme/DESCRIPTION.rst
  product_english_name/security/groups.xml
  product_english_name/static/description/icon.png
  product_english_name/static/description/index.html
  product_english_name/static/description/screen_english.png
  product_english_name/static/description/screen_french.png
  product_english_name/views/product_template.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/product_english_name/odoo/addons/product_english_name
  setup/product_english_name/setup.py
Labels: 16.0

#1171 Syncing from upstream OCA/product-attribute (16.0)
  README.md
  product_profile/README.rst
  product_profile/__manifest__.py
  product_profile/models/product_profile.py
Labels: 16.0

#1172 Syncing from upstream OCA/product-attribute (16.0)
  product_english_name/i18n/it.po
Labels: 16.0

#1173 Syncing from upstream OCA/product-attribute (18.0)
  .copier-answers.yml
  .eslintrc.yml
  .pre-commit-config.yaml
  .prettierrc.yml
  eslint.config.cjs
  prettier.config.cjs
Labels: 18.0

#1174 [t153388][PB][ADD] product_manufacturer
  product_manufacturer/README.rst
  product_manufacturer/__init__.py
  product_manufacturer/__manifest__.py
  product_manufacturer/i18n/ar.po
  product_manufacturer/i18n/bg.po
  product_manufacturer/i18n/bs.po
  product_manufacturer/i18n/ca.po
  product_manufacturer/i18n/cs.po
  product_manufacturer/i18n/da.po
  product_manufacturer/i18n/de.po
  product_manufacturer/i18n/el.po
  product_manufacturer/i18n/es.po
  product_manufacturer/i18n/es_AR.po
  product_manufacturer/i18n/es_CR.po
  product_manufacturer/i18n/es_EC.po
  product_manufacturer/i18n/es_MX.po
  product_manufacturer/i18n/es_VE.po
  product_manufacturer/i18n/et.po
  product_manufacturer/i18n/fi.po
  product_manufacturer/i18n/fr.po
  product_manufacturer/i18n/gl.po
  product_manufacturer/i18n/hr.po
  product_manufacturer/i18n/hu.po
  product_manufacturer/i18n/it.po
  product_manufacturer/i18n/ja.po
  product_manufacturer/i18n/lt.po
  product_manufacturer/i18n/lv.po
  product_manufacturer/i18n/mk.po
  product_manufacturer/i18n/mn.po
  product_manufacturer/i18n/nb.po
  product_manufacturer/i18n/nl.po
  product_manufacturer/i18n/nl_NL.po
  product_manufacturer/i18n/pl.po
  product_manufacturer/i18n/product_manufacturer.pot
  product_manufacturer/i18n/pt.po
  product_manufacturer/i18n/pt_BR.po
  product_manufacturer/i18n/ro.po
  product_manufacturer/i18n/ru.po
  product_manufacturer/i18n/sl.po
  product_manufacturer/i18n/sr.po
  product_manufacturer/i18n/sr@latin.po
  product_manufacturer/i18n/sv.po
  product_manufacturer/i18n/tr.po
  product_manufacturer/i18n/zh_CN.po
  product_manufacturer/i18n/zh_TW.po
  product_manufacturer/models/__init__.py
  product_manufacturer/models/product_product.py
  product_manufacturer/models/product_template.py
  product_manufacturer/pyproject.toml
  product_manufacturer/readme/CONTRIBUTORS.md
  product_manufacturer/readme/DESCRIPTION.md
  product_manufacturer/static/description/icon.png
  product_manufacturer/static/description/index.html
  product_manufacturer/tests/__init__.py
  product_manufacturer/tests/test_product_manufacturer.py
  product_manufacturer/views/product_manufacturer_view.xml
Labels: 17.0.project_go_755

#1176 Syncing from upstream OCA/product-attribute (18.0)
  README.md
  product_dimension/README.rst
  product_dimension/__init__.py
  product_dimension/__manifest__.py
  product_dimension/i18n/ca.po
  product_dimension/i18n/de.po
  product_dimension/i18n/es.po
  product_dimension/i18n/fr.po
  product_dimension/i18n/fr_FR.po
  product_dimension/i18n/it.po
  product_dimension/i18n/product_dimension.pot
  product_dimension/i18n/pt.po
  product_dimension/models/__init__.py
  product_dimension/models/product_product.py
  product_dimension/models/product_template.py
  product_dimension/pyproject.toml
  product_dimension/readme/CONTRIBUTORS.md
  product_dimension/readme/CREDITS.md
  product_dimension/readme/DESCRIPTION.md
  product_dimension/readme/HISTORY.md
  product_dimension/readme/USAGE.md
  product_dimension/static/description/icon.png
  product_dimension/static/description/index.html
  product_dimension/tests/__init__.py
  product_dimension/tests/test_compute_volume.py
  product_dimension/tests/test_template.py
  product_dimension/views/product_view.xml
  setup/_metapackage/pyproject.toml
Labels: 18.0

#1177 Syncing from upstream OCA/product-attribute (14.0)
  product_attribute_variant_rules/i18n/it.po
Labels: 14.0

#1178 Syncing from upstream OCA/product-attribute (16.0)
  product_pricelist_simulation/i18n/fr.po
  product_pricelist_simulation_margin/i18n/fr.po
Labels: 16.0
