Repository brain-tec/product-attribute, pull requests merged in 2024-06, with the labels that each got.

#1099 Syncing from upstream OCA/product-attribute (17.0)
  README.md
  product_supplierinfo_for_customer/README.rst
  product_supplierinfo_for_customer/__manifest__.py
  product_supplierinfo_for_customer/models/product_supplierinfo.py
  product_supplierinfo_for_customer/static/description/index.html
Labels: 17.0

#1100 Syncing from upstream OCA/product-attribute (14.0)
  product_restricted_type/i18n/fr.po
Labels: 14.0

#1101 Syncing from upstream OCA/product-attribute (16.0)
  README.md
  product_attribute_value_menu/README.rst
  product_attribute_value_menu/__manifest__.py
  product_attribute_value_menu/static/description/index.html
  product_attribute_value_menu/views/product_attribute_value_views.xml
Labels: 16.0

#1102 Syncing from upstream OCA/product-attribute (12.0)
  product_logistics_uom/i18n/it.po
Labels: 12.0

#1103 Syncing from upstream OCA/product-attribute (14.0)
  product_logistics_uom/i18n/it.po
  product_packaging_dimension/i18n/it.po
Labels: 14.0

#1104 Syncing from upstream OCA/product-attribute (15.0)
  product_logistics_uom/i18n/it.po
Labels: 15.0

#1105 Syncing from upstream OCA/product-attribute (16.0)
  product_logistics_uom/i18n/it.po
  product_packaging_dimension/i18n/it.po
Labels: 16.0

#1106 Syncing from upstream OCA/product-attribute (17.0)
  product_sequence/i18n/sv.po
  product_set/i18n/sv.po
Labels: 17.0

#1108 Syncing from upstream OCA/product-attribute (14.0)
  product_category_type/i18n/fr.po
  product_restricted_type/i18n/fr.po
Labels: 14.0

#1109 Syncing from upstream OCA/product-attribute (16.0)
  README.md
  product_logistics_uom/README.rst
  product_logistics_uom/__manifest__.py
  product_logistics_uom/models/product_template.py
  product_logistics_uom/static/description/index.html
  product_logistics_uom/tests/test_product_logistics_uom.py
  product_pricelist_direct_print/README.rst
  product_pricelist_direct_print/__manifest__.py
  product_pricelist_direct_print/i18n/es.po
  product_pricelist_direct_print/i18n/fr.po
  product_pricelist_direct_print/i18n/it.po
  product_pricelist_direct_print/i18n/product_pricelist_direct_print.pot
  product_pricelist_direct_print/i18n/tr.po
  product_pricelist_direct_print/static/description/index.html
  product_pricelist_direct_print/wizards/product_pricelist_print.py
  product_pricelist_direct_print/wizards/product_pricelist_print_view.xml
Labels: 16.0

#1110 Syncing from upstream OCA/product-attribute (16.0)
  README.md
  product_cost_security/README.rst
  product_cost_security/__manifest__.py
  product_cost_security/i18n/ar.po
  product_cost_security/i18n/ca.po
  product_cost_security/i18n/es.po
  product_cost_security/i18n/it.po
  product_cost_security/i18n/product_cost_security.pot
  product_cost_security/models/__init__.py
  product_cost_security/models/product_supplierinfo.py
  product_cost_security/static/description/index.html
  product_supplierinfo_for_customer/i18n/ca.po
  product_supplierinfo_for_customer/i18n/de.po
  product_supplierinfo_for_customer/i18n/es.po
  product_supplierinfo_for_customer/i18n/fr.po
  product_supplierinfo_for_customer/i18n/it.po
  product_supplierinfo_for_customer/i18n/product_supplierinfo_for_customer.pot
  product_supplierinfo_for_customer/i18n/pt_BR.po
  product_supplierinfo_for_customer/i18n/sl.po
Labels: 16.0

#1112 [MIG] Not yet merged in OCA: `17.0 mig product pricelist supplierinfo`
  product_pricelist_supplierinfo/README.rst
  product_pricelist_supplierinfo/__init__.py
  product_pricelist_supplierinfo/__manifest__.py
  product_pricelist_supplierinfo/i18n/ca.po
  product_pricelist_supplierinfo/i18n/es.po
  product_pricelist_supplierinfo/i18n/fr.po
  product_pricelist_supplierinfo/i18n/it.po
  product_pricelist_supplierinfo/i18n/nl.po
  product_pricelist_supplierinfo/i18n/product_pricelist_supplierinfo.pot
  product_pricelist_supplierinfo/i18n/pt_BR.po
  product_pricelist_supplierinfo/models/__init__.py
  product_pricelist_supplierinfo/models/product_pricelist_item.py
  product_pricelist_supplierinfo/models/product_product.py
  product_pricelist_supplierinfo/models/product_supplierinfo.py
  product_pricelist_supplierinfo/models/product_template.py
  product_pricelist_supplierinfo/pyproject.toml
  product_pricelist_supplierinfo/readme/CONFIGURE.md
  product_pricelist_supplierinfo/readme/CONTRIBUTORS.md
  product_pricelist_supplierinfo/readme/DESCRIPTION.md
  product_pricelist_supplierinfo/readme/INSTALL.md
  product_pricelist_supplierinfo/readme/ROADMAP.md
  product_pricelist_supplierinfo/readme/USAGE.md
  product_pricelist_supplierinfo/security/res_groups.xml
  product_pricelist_supplierinfo/static/description/icon.png
  product_pricelist_supplierinfo/static/description/index.html
  product_pricelist_supplierinfo/tests/__init__.py
  product_pricelist_supplierinfo/tests/test_product_supplierinfo.py
  product_pricelist_supplierinfo/views/product_pricelist_item_views.xml
  product_pricelist_supplierinfo/views/product_supplierinfo_view.xml
Labels: 17.0.project_ba_688

#1113 Syncing from upstream OCA/product-attribute (16.0)
  pos_product_cost_security/i18n/it.po
Labels: 16.0

#1114 Syncing from upstream OCA/product-attribute (16.0)
  README.md
  product_pricelist_alternative/README.rst
  product_pricelist_alternative/__manifest__.py
  product_pricelist_alternative/models/product_pricelist.py
  product_pricelist_alternative/static/description/index.html
  product_pricelist_alternative/tests/common.py
  product_pricelist_alternative/tests/test_pricelist_alternative.py
Labels: 16.0

#1115 Syncing from upstream OCA/product-attribute (17.0)
  README.md
  product_pricelist_supplierinfo/README.rst
  product_pricelist_supplierinfo/__init__.py
  product_pricelist_supplierinfo/__manifest__.py
  product_pricelist_supplierinfo/i18n/ca.po
  product_pricelist_supplierinfo/i18n/es.po
  product_pricelist_supplierinfo/i18n/fr.po
  product_pricelist_supplierinfo/i18n/it.po
  product_pricelist_supplierinfo/i18n/nl.po
  product_pricelist_supplierinfo/i18n/product_pricelist_supplierinfo.pot
  product_pricelist_supplierinfo/i18n/pt_BR.po
  product_pricelist_supplierinfo/models/__init__.py
  product_pricelist_supplierinfo/models/product_pricelist_item.py
  product_pricelist_supplierinfo/models/product_product.py
  product_pricelist_supplierinfo/models/product_supplierinfo.py
  product_pricelist_supplierinfo/models/product_template.py
  product_pricelist_supplierinfo/pyproject.toml
  product_pricelist_supplierinfo/readme/CONFIGURE.md
  product_pricelist_supplierinfo/readme/CONTRIBUTORS.md
  product_pricelist_supplierinfo/readme/DESCRIPTION.md
  product_pricelist_supplierinfo/readme/INSTALL.md
  product_pricelist_supplierinfo/readme/ROADMAP.md
  product_pricelist_supplierinfo/readme/USAGE.md
  product_pricelist_supplierinfo/security/res_groups.xml
  product_pricelist_supplierinfo/static/description/icon.png
  product_pricelist_supplierinfo/static/description/index.html
  product_pricelist_supplierinfo/tests/__init__.py
  product_pricelist_supplierinfo/tests/test_product_supplierinfo.py
  product_pricelist_supplierinfo/views/product_pricelist_item_views.xml
  product_pricelist_supplierinfo/views/product_supplierinfo_view.xml
  product_supplierinfo_for_customer/i18n/ca.po
  product_supplierinfo_for_customer/i18n/de.po
  product_supplierinfo_for_customer/i18n/es.po
  product_supplierinfo_for_customer/i18n/fr.po
  product_supplierinfo_for_customer/i18n/it.po
  product_supplierinfo_for_customer/i18n/product_supplierinfo_for_customer.pot
  product_supplierinfo_for_customer/i18n/pt_BR.po
  product_supplierinfo_for_customer/i18n/sl.po
  setup/_metapackage/pyproject.toml
Labels: 17.0
