Repository brain-tec/product-attribute, pull requests merged in 2024-07, with the labels that each got.

#1117 Syncing from upstream OCA/product-attribute (17.0)
  product_supplierinfo_for_customer/i18n/it.po
Labels: 17.0

#1118 [t140653] Rename product_product fields
  product_dimension/migrations/16.0.1.1.0/pre-migration.py
Labels: 16.0.project_xp_228

#1119 Syncing from upstream OCA/product-attribute (17.0)
  product_pricelist_supplierinfo/i18n/ca.po
  product_pricelist_supplierinfo/i18n/es.po
  product_pricelist_supplierinfo/i18n/fr.po
  product_pricelist_supplierinfo/i18n/it.po
  product_pricelist_supplierinfo/i18n/nl.po
  product_pricelist_supplierinfo/i18n/pt_BR.po
Labels: 17.0

#1120 Syncing from upstream OCA/product-attribute (16.0)
  README.md
  product_pricelist_direct_print/README.rst
  product_pricelist_direct_print/__manifest__.py
  product_pricelist_direct_print/i18n/es.po
  product_pricelist_direct_print/i18n/fr.po
  product_pricelist_direct_print/i18n/it.po
  product_pricelist_direct_print/i18n/product_pricelist_direct_print.pot
  product_pricelist_direct_print/i18n/tr.po
  product_pricelist_direct_print/readme/CONTRIBUTORS.rst
  product_pricelist_direct_print/static/description/index.html
  product_pricelist_direct_print/wizards/product_pricelist_print.py
  product_pricelist_direct_print/wizards/product_pricelist_print_view.xml
  product_sequence/i18n/hr.po
Labels: 16.0

#1121 Syncing from upstream OCA/product-attribute (17.0)
  product_pricelist_supplierinfo/i18n/it.po
Labels: 17.0

#1122 Syncing from upstream OCA/product-attribute (16.0)
  product_pricelist_direct_print/i18n/it.po
Labels: 16.0

#1123 Syncing from upstream OCA/product-attribute (16.0)
  README.md
  product_assortment/README.rst
  product_assortment/__manifest__.py
  product_assortment/data/ir_cron.xml
  product_assortment/i18n/ca.po
  product_assortment/i18n/de.po
  product_assortment/i18n/es.po
  product_assortment/i18n/it.po
  product_assortment/i18n/product_assortment.pot
  product_assortment/models/ir_filters.py
  product_assortment/models/res_partner.py
  product_assortment/static/description/index.html
Labels: 16.0

#1124 Syncing from upstream OCA/product-attribute (16.0)
  product_assortment/i18n/it.po
Labels: 16.0

#1125 Syncing from upstream OCA/product-attribute (17.0)
  README.md
  product_code_unique/README.rst
  product_code_unique/__init__.py
  product_code_unique/__manifest__.py
  product_code_unique/hook.py
  product_code_unique/i18n/ca.po
  product_code_unique/i18n/de.po
  product_code_unique/i18n/es.po
  product_code_unique/i18n/fr.po
  product_code_unique/i18n/fr_FR.po
  product_code_unique/i18n/it.po
  product_code_unique/i18n/product_code_unique.pot
  product_code_unique/i18n/pt.po
  product_code_unique/models/__init__.py
  product_code_unique/models/product.py
  product_code_unique/pyproject.toml
  product_code_unique/readme/CONTRIBUTORS.md
  product_code_unique/readme/DESCRIPTION.md
  product_code_unique/readme/ROADMAP.md
  product_code_unique/readme/USAGE.md
  product_code_unique/static/description/icon.png
  product_code_unique/static/description/index.html
  product_code_unique/tests/__init__.py
  product_code_unique/tests/test_code_unique.py
  product_logistics_uom/README.rst
  product_logistics_uom/__init__.py
  product_logistics_uom/__manifest__.py
  product_logistics_uom/hooks.py
  product_logistics_uom/i18n/de.po
  product_logistics_uom/i18n/es.po
  product_logistics_uom/i18n/it.po
  product_logistics_uom/i18n/product_logistics_uom.pot
  product_logistics_uom/i18n/pt_BR.po
  product_logistics_uom/models/__init__.py
  product_logistics_uom/models/product_product.py
  product_logistics_uom/models/product_template.py
  product_logistics_uom/models/res_config_settings.py
  product_logistics_uom/pyproject.toml
  product_logistics_uom/readme/CONFIGURE.md
  product_logistics_uom/readme/CONTRIBUTORS.md
  product_logistics_uom/readme/CREDITS.md
  product_logistics_uom/readme/DESCRIPTION.md
  product_logistics_uom/readme/INSTALL.md
  product_logistics_uom/readme/USAGE.md
  product_logistics_uom/static/description/icon.png
  product_logistics_uom/static/description/index.html
  product_logistics_uom/tests/__init__.py
  product_logistics_uom/tests/test_product_logistics_uom.py
  product_logistics_uom/views/product.xml
  product_logistics_uom/views/res_config_settings.xml
  setup/_metapackage/pyproject.toml
Labels: 17.0

#1126 Syncing from upstream OCA/product-attribute (17.0)
  product_logistics_uom/i18n/it.po
Labels: 17.0

#1127 Syncing from upstream OCA/product-attribute (16.0)
  README.md
  product_template_tags/README.rst
  product_template_tags/__manifest__.py
  product_template_tags/i18n/ca_ES.po
  product_template_tags/i18n/de.po
  product_template_tags/i18n/es.po
  product_template_tags/i18n/fr.po
  product_template_tags/i18n/hr.po
  product_template_tags/i18n/it.po
  product_template_tags/i18n/nl.po
  product_template_tags/i18n/product_template_tags.pot
  product_template_tags/i18n/pt.po
  product_template_tags/i18n/sl_SI.po
  product_template_tags/models/product_template_tag.py
  product_template_tags/static/description/index.html
  product_template_tags/views/product_template_tag.xml
Labels: 16.0

#1128 Syncing from upstream OCA/product-attribute (16.0)
  product_template_tags/i18n/it.po
Labels: 16.0
